// tests/unittests/test_qwen3_asr_bpe_parity.cpp - Phase 10.5 HF byte-level
// BPE parity gate for the engine Qwen3-ASR tokenizer.
//
// Ported from transcribe.cpp's tests/transcribe/qwen3_asr_bpe_parity.cpp
// (retired with src/runtime/arch/qwen3_asr/) onto the engine package. Same
// fixture file - tests/fixtures/qwen3_asr_bpe_parity.inc, generated by
// scripts/tokenizer-parity-fixture.py from the HF tokenizer bundled with the
// 0.6B checkpoint - now asserted against
// engine::models::qwen3_asr::Qwen3ASRTextTokenizer, the exact encoder that
// build_prompt() runs.
//
//   1. k_bpe_fixtures: plain strings must encode token-for-token to what HF's
//      tokenizer produces for encode(add_special_tokens=False).
//   2. k_lang_prefix_fixtures: for each of the 30 publisher languages the
//      forced-language chat seed "language {Name}<asr_text>" must tokenize
//      to BPE("language {Name}") + the <asr_text> special id. Checked on the
//      literal string AND on the tail of build_prompt() fed the BCP-47 code,
//      which is the arch's encode_language_prefix() contract: the engine
//      must accept "en" as well as "English".
//
// Skips (exit 2) while the pinned GGUF is absent
// (scripts/fetch_asr_test_model.py).

#include "engine/models/qwen3_asr/assets.h"
#include "engine/models/qwen3_asr/languages.h"
#include "engine/models/qwen3_asr/tokenizer_text.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <exception>
#include <filesystem>
#include <string>
#include <vector>

namespace {

int g_failures = 0;

// Fixture schema used by the generated .inc file (LangFixture is defined by
// the .inc itself).
struct Fixture {
    const char *  text;
    const int32_t ids[32];
    size_t        n_ids;
};

#include "fixtures/qwen3_asr_bpe_parity.inc"

void check_ids_equal(const char *                 label,
                     const char *                 text,
                     const int32_t *              expected,
                     size_t                       expected_n,
                     const std::vector<int32_t> & actual) {
    if (actual.size() == expected_n && std::memcmp(actual.data(), expected, expected_n * sizeof(int32_t)) == 0) {
        return;
    }
    ++g_failures;
    std::fprintf(stderr, "FAIL[%s] input=\"%s\"\n  expected (%zu):", label, text, expected_n);
    for (size_t i = 0; i < expected_n; ++i) {
        std::fprintf(stderr, " %d", static_cast<int>(expected[i]));
    }
    std::fprintf(stderr, "\n  actual   (%zu):", actual.size());
    for (const int32_t id : actual) {
        std::fprintf(stderr, " %d", static_cast<int>(id));
    }
    std::fprintf(stderr, "\n");
}

}  // namespace

int main(int argc, char ** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: qwen3_asr_bpe_parity_test <qwen3-asr.gguf>\n");
        return 1;
    }
    const std::filesystem::path model_path = argv[1];
    if (!std::filesystem::exists(model_path)) {
        std::printf("SKIP: pinned Qwen3-ASR GGUF not found: %s\n", model_path.string().c_str());
        return 2;
    }

    try {
        const auto assets = engine::models::qwen3_asr::load_qwen3_asr_assets(model_path);
        const engine::models::qwen3_asr::Qwen3ASRTextTokenizer tokenizer(assets);

        // Section 1: plain-text BPE parity.
        std::printf("qwen3_asr_bpe_parity_test: %zu plain BPE fixtures\n", k_bpe_fixtures_n);
        for (size_t i = 0; i < k_bpe_fixtures_n; ++i) {
            const auto & f = k_bpe_fixtures[i];
            check_ids_equal("bpe", f.text, f.ids, f.n_ids, tokenizer.encode(f.text));
        }

        // Section 2: language-prefix parity, literal string and prompt tail.
        std::printf("qwen3_asr_bpe_parity_test: %zu language-prefix fixtures\n", k_lang_prefix_fixtures_n);
        for (size_t i = 0; i < k_lang_prefix_fixtures_n; ++i) {
            const auto & f = k_lang_prefix_fixtures[i];
            char label[64];

            std::snprintf(label, sizeof(label), "lang-literal %s", f.bcp47);
            const std::string literal = std::string("language ") + f.pub_name + "<asr_text>";
            check_ids_equal(label, literal.c_str(), f.ids, f.n_ids, tokenizer.encode(literal));

            // The engine must accept the BCP-47 code the C ABI speaks and seed
            // the assistant turn with exactly the fixture ids.
            std::snprintf(label, sizeof(label), "lang-prompt %s", f.bcp47);
            const auto mapped = engine::models::qwen3_asr::qwen3_asr_language_name_from_bcp47(f.bcp47);
            if (!mapped.has_value() || *mapped != f.pub_name) {
                ++g_failures;
                std::fprintf(stderr, "FAIL[%s] language table maps \"%s\" to \"%s\", fixture says \"%s\"\n", label,
                             f.bcp47, mapped.has_value() ? mapped->c_str() : "<none>", f.pub_name);
                continue;
            }
            const auto prompt = tokenizer.build_prompt("", f.bcp47, /*audio_feature_tokens=*/1);
            if (prompt.input_ids.size() < f.n_ids) {
                ++g_failures;
                std::fprintf(stderr, "FAIL[%s] prompt shorter than the language prefix\n", label);
                continue;
            }
            const std::vector<int32_t> tail(prompt.input_ids.end() - static_cast<std::ptrdiff_t>(f.n_ids),
                                            prompt.input_ids.end());
            check_ids_equal(label, f.pub_name, f.ids, f.n_ids, tail);
        }
    } catch (const std::exception & error) {
        std::fprintf(stderr, "FAIL: %s\n", error.what());
        return 1;
    }

    if (g_failures > 0) {
        std::fprintf(stderr, "qwen3_asr_bpe_parity_test: %d failure(s)\n", g_failures);
        return 1;
    }
    std::printf("qwen3_asr_bpe_parity_test: PASS\n");
    return 0;
}
